# This workflow will build and test Java project with Maven. It will also test javascript with Jest
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maptivist CI with Maven/Jest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  java:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file maptivist/pom.xml
    - name: Test with Maven
      run: mvn test --file maptivist/pom.xml
      
  javascript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn jest
